In [7]:
import pandas as pd

In [8]:
import os
import glob
import ast


directory = 'good'
my_files = [f for f in glob.glob(os.path.join(directory, "*.csv"))]
# infile = 'good/llama70b_rps.csv'

for infile in my_files:
    df = pd.read_csv(infile)
    sml = df.drop(['id', 'prompt', 'samples'], axis=1)
    sml.head()
    import ast
    def parse_json(row):
        parsed_json = ast.literal_eval(row)
        title = parsed_json.get('MovieName', '')
        predicted_rating = parsed_json.get('RatingPrediction', '')
        return title, predicted_rating
    sml[['title', 'predicted_rating']] = sml['json'].apply(parse_json).apply(pd.Series)
    sml['title'] = sml['title'].apply(lambda x: x.split(')-')[0]+')')
    fin = sml.drop(columns=['json'])
    outfile = infile.split('/')[-1]
    fin.to_csv('llm_output_processed/'+outfile, index=False)

In [9]:
mov_df = pd.read_csv('orig_data/movies.csv')
rate_df = pd.read_csv('orig_data/ratings.csv')
comp_df = rate_df.merge(mov_df, on='movieId')
comp_df

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
...,...,...,...,...,...,...
100831,610,166534,4.0,1493848402,Split (2017),Drama|Horror|Thriller
100832,610,168248,5.0,1493850091,John Wick: Chapter Two (2017),Action|Crime|Thriller
100833,610,168250,5.0,1494273047,Get Out (2017),Horror
100834,610,168252,5.0,1493846352,Logan (2017),Action|Sci-Fi
100835,610,170875,3.0,1493846415,The Fate of the Furious (2017),Action|Crime|Drama|Thriller

In [10]:
comp_df.drop(columns=['movieId', 'timestamp', 'genres'], inplace=True)
comp_df.head()

   userId  rating                        title
0       1     4.0             Toy Story (1995)
1       1     4.0      Grumpier Old Men (1995)
2       1     4.0                  Heat (1995)
3       1     5.0  Seven (a.k.a. Se7en) (1995)
4       1     5.0   Usual Suspects, The (1995)

In [11]:
comp_df.to_csv('orig_data/all_ratings.csv', index=False)